<?xml version="1.0"?>
<package format="3">
  <name>mecanum_description</name>
  <version>0.1.0</version>
  <description>Reusable visual description assets for the XGC2 Mecanum UGV.</description>

  <maintainer email="lxk@xiaokang.local">lxk</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>urdf</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
